name: ST-AlphaChest
main: net.starly.alphachest.AlphaChestMain
author: Starly Team
website: http://starly.kr/

description: AlphaChest Plugin.

softdepend:
  - ST-Core

version: 1.0.2
api-version: 1.13

commands:
  가상창고: